version: "1.0.0"
env: "dev"
httpd:
  host: "0.0.0.0"
  port: 8010
log:
  dir: "/tmp/logs"
  name: "webshell.log"
  format: ""
  retainDay: 3
  Level: "INFO"
mysql:
  host: "127.0.0.1"
  port: 3306
  db: "portal"
  user: "root"
  password: "123456"


